CREATE TABLE IF NOT EXISTS MF_DOCUMENT
(
   DOCUMENT_GUID                  char(36)                       not null,
   ACOUNT_GUID                    char(36)                       not null,
   DOCUMENT_TITLE                 varchar(768)                   not null,
   DIR_GUID                       char(36),                       
   DOCUMENT_LOCATION              varchar(768),
   DOCUMENT_NAME                  varchar(300),
   DOCUMENT_SEO                   varchar(300),
   DOCUMENT_URL                   varchar(2048),
   DOCUMENT_AUTHOR                varchar(150),
   DOCUMENT_KEYWORDS              varchar(300),
   DOCUMENT_TYPE                  varchar(20),
   DOCUMENT_OWNER                 varchar(150),
   DT_CREATED                     char(19),
   DT_MODIFIED                    char(19),
   DT_ACCESSED                    char(19),
   DOCUMENT_ICON_INDEX            int,
   DOCUMENT_SYNC                  int                         default 0,
   DOCUMENT_PROTECT               varchar(50),
   DOCUMENT_ENCODE                char(1)                     default '0',
   DOCUMENT_READ_COUNT            int                         default 0,
   DOCUMENT_RELATE_COUNT          int                         default 0,
   DOCUMENT_INDEXFLG              char(1)                     default '0',
   DOCUMENT_OPERFLG               char(1)                     default '0',
   DELETE_FLAG                    char(1)                     default 0,
   MF_VERSION                     int64                       default 0,
   primary key (DOCUMENT_GUID)
)