SELECT    MF_TAG.TAG_GUID,
          MF_TAG.TAG_NAME,
          MF_TAG.TAG_GROUP_GUID,
          MF_TAG.TAG_DESCRIPTION,
          MF_TAG.DT_MODIFIED,
          MF_TAG.MF_VERSION
FROM
   MF_TAG
LEFT OUTER JOIN MF_DOCUMENT_TAG 
ON MF_TAG.TAG_GUID = MF_DOCUMENT_TAG.TAG_GUID 
WHERE MF_DOCUMENT_TAG.DOCUMENT_GUID='%1'
