UPDATE TABLE 
    MF_TAG 
SET TAG_NAME='%1' 
    AND TAG_DESCRIPTION='%2' 
    AND TAG_GROUP_GUID='%3'
    AND MF_VERSION='%4' 
    AND DT_MODIFIED=datetime(CURRENT_TIMESTAMP,'localtime')
WHERE TAG_GUID='%5'
