//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FsUi.rc
//
#define IDS_SEARCH_PATH                 1
#define IDS_OBJECT_TYPE                 2
#define IDS_OK                          3
#define IDS_CANCEL                      4
#define IDS_DELETE                      5
#define IDS_NEW_WORDS                   6
#define IDS_CLOSE                       7
#define IDS_CUSTOM_CIHUI                8
#define IDS_CIHUI_1                     9
#define IDS_IMPORT_CIHUI                10
#define IDS_CIHUI_2                     11
#define IDS_CIHUI_3                     12
#define IDS_CHECK_OVERCIHUI             13
#define IDS_CHECK_EXISTCIHUI            14
#define IDS_SOFT_SET                    15
#define IDS_SET_1                       16
#define IDS_LICENSE_INFO                17
#define IDS_LICENSE_1                   18
#define IDS_NUM                         19
#define IDS_STATIC_EMAIL                20
#define IDS_BEGINTIME                   21
#define IDS_ENDTIME                     22
#define IDS_BEGINTIME_CONTENT           23
#define IDS_ENTTIME_CONTENT             24
#define IDS_ERROR_INFO                  25
#define IDS_REG                         26
#define IDS_NEW_INDEX                   27
#define IDS_MODIFY_INDEX                28
#define IDS_DEL_INDEX                   29
#define IDS_SELECT_PATH                 30
#define IDS_SELECT_OBJECT               31
#define IDS_PATH_EXISTS                 32
#define IDS_SELECT_FILE                 33
#define IDS_MODIFY_INDEX_OK             34
#define IDS_NO_DEALWITH                 35
#define IDS_DEL_INDEX_OK                36
#define IDS_SHEET_SYS_SET               37
#define IDS_BASIC_SET                   38
#define IDS_SET_NOMARL                  39
#define IDS_CUSTOM_CH                   40
#define IDS_LICENSE_MANAGE              41
#define IDS_SET_LICENSE_INFO            42
#define IDS_SEARCH_PATH_JP              43
#define IDS_OBJECT_TYPE_JP              44
#define IDS_OK_JP                       45
#define IDS_CANCEL_JP                   46
#define IDS_DELETE_JP                   47
#define IDS_NEW_WORDS_JP                48
#define IDS_CLOSE_JP                    49
#define IDS_CUSTOM_CIHUI_JP             50
#define IDS_CIHUI_1_JP                  51
#define IDS_IMPORT_CIHUI_JP             52
#define IDS_CIHUI_2_JP                  53
#define IDS_CIHUI_3_JP                  54
#define IDS_CHECK_OVERCIHUI_JP          55
#define IDS_CHECK_EXISTCIHUI_JP         56
#define IDS_SOFT_SET_JP                 57
#define IDS_SET_1_JP                    58
#define IDS_LICENSE_INFO_JP             59
#define IDS_LICENSE_1_JP                60
#define IDS_NUM_JP                      61
#define IDS_STATIC_EMAIL_JP             62
#define IDS_BEGINTIME_JP                63
#define IDS_ENDTIME_JP                  64
#define IDS_BEGINTIME_CONTENT_JP        65
#define IDS_ENTTIME_CONTENT_JP          66
#define IDS_ERROR_INFO_JP               67
#define IDS_REG_JP                      68
#define IDS_NEW_INDEX_JP                69
#define IDS_MODIFY_INDEX_JP             70
#define IDS_DEL_INDEX_JP                71
#define IDS_SELECT_PATH_JP              72
#define IDS_SELECT_OBJECT_JP            73
#define IDS_PATH_EXISTS_JP              74
#define IDS_SELECT_FILE_JP              75
#define IDS_MODIFY_INDEX_OK_JP          76
#define IDS_NO_DEALWITH_JP              77
#define IDS_DEL_INDEX_OK_JP             78
#define IDS_SHEET_SYS_SET_JP            79
#define IDS_BASIC_SET_JP                80
#define IDS_SET_NOMARL_JP               81
#define IDS_CUSTOM_CH_JP                82
#define IDS_LICENSE_MANAGE_JP           83
#define IDS_SET_LICENSE_INFO_JP         84
#define IDS_SEARCH_PATH_EN              85
#define IDS_OBJECT_TYPE_EN              86
#define IDS_OK_EN                       87
#define IDS_CANCEL_EN                   88
#define IDS_DELETE_EN                   89
#define IDS_NEW_WORDS_EN                90
#define IDS_CLOSE_EN                    91
#define IDS_CUSTOM_CIHUI_EN             92
#define IDS_CIHUI_1_EN                  93
#define IDS_IMPORT_CIHUI_EN             94
#define IDS_CIHUI_2_EN                  95
#define IDS_CIHUI_3_EN                  96
#define IDS_CHECK_OVERCIHUI_EN          97
#define IDS_CHECK_EXISTCIHUI_EN         98
#define IDS_SOFT_SET_EN                 99
#define IDS_SET_1_EN                    100
#define IDS_LICENSE_INFO_EN             101
#define IDS_LICENSE_1_EN                102
#define IDS_NUM_EN                      103
#define IDS_STATIC_EMAIL_EN             104
#define IDS_BEGINTIME_EN                105
#define IDS_ENDTIME_EN                  106
#define IDS_BEGINTIME_CONTENT_EN        107
#define IDS_ENTTIME_CONTENT_EN          108
#define IDS_ERROR_INFO_EN               109
#define IDS_REG_EN                      110
#define IDS_NEW_INDEX_EN                111
#define IDS_MODIFY_INDEX_EN             112
#define IDS_DEL_INDEX_EN                113
#define IDS_SELECT_PATH_EN              114
#define IDS_SELECT_OBJECT_EN            115
#define IDS_PATH_EXISTS_EN              116
#define IDS_SELECT_FILE_EN              117
#define IDS_MODIFY_INDEX_OK_EN          118
#define IDS_NO_DEALWITH_EN              119
#define IDS_DEL_INDEX_OK_EN             120
#define IDS_SHEET_SYS_SET_EN            121
#define IDS_BASIC_SET_EN                122
#define IDS_SET_NOMARL_EN               123
#define IDS_CUSTOM_CH_EN                124
#define IDS_LICENSE_MANAGE_EN           125
#define IDS_SET_LICENSE_INFO_EN         126
#define IDD_DIALOG_CREATE_INDEX         2000
#define IDC_EDIT_SEARCH_PATH            2000
#define IDC_BUTTON_BROWSE               2001
#define IDD_DIALOG_CUSTOM_DICT          2001
#define IDC_CHECK_EXCEL                 2002
#define IDD_DIALOG_MODIFY_INDEX         2002
#define IDC_CHECK_WORD                  2003
#define IDC_EDIT_CIHUI_PATH             2003
#define IDD_DIALOG_ALL_CIHUI            2003
#define IDC_CHECK_PPT                   2004
#define IDC_BUTTON_BROWSE_CIHUI         2004
#define IDC_CHECK_PDF                   2005
#define IDC_CHECK_OVERCIHUI             2005
#define IDD_DIALOG_SET_ATTR             2005
#define IDC_CHECK_HTML                  2006
#define IDC_BUTTON_CHECK_EXISTCIHUI     2006
#define IDD_DIALOG_FAST_SEARCH          2006
#define IDC_CHECK_TXT                   2007
#define IDC_STATIC_SEARCHPATH           2007
#define IDI_ICON_WORD                   2007
#define IDC_CHECK_TXT_MODIFY            2008
#define IDI_ICON_EXCEL                  2008
#define IDC_CHECK_CHM                   2009
#define IDI_ICON_PPT                    2009
#define IDC_BUTTON_DEL_INDEX            2010
#define IDI_ICON_PDF                    2010
#define IDC_LIST_ALL_CIHUI              2011
#define IDI_ICON_TXT                    2011
#define IDC_EDIT_KEY_WORD               2012
#define IDD_DIALOG_LICENSE              2012
#define IDC_EDIT_IE_PATH                2013
#define IDI_ICON_SYS_SET                2013
#define IDC_EDIT_WORD_PATH              2014
#define IDI_ICON_SET_NORMAL             2014
#define IDC_EDIT_EXCEL_PATH             2015
#define IDC_EDIT_PPT_PATH               2016
#define IDC_EDIT_PDF_PATH               2017
#define IDC_EDIT_TXT_PATH               2018
#define IDC_BUTTON_BROWSER_IE           2019
#define IDI_ICON_SET_TOOLS              2019
#define IDC_BUTTON_BROWSER_WORD         2020
#define IDC_EDIT_SEARCH_KEY             2020
#define IDI_ICON_CIHUI                  2020
#define IDC_BUTTON_BROWSER_EXCEL        2021
#define IDC_COMBO_PATH                  2021
#define IDI_ICON_CIHUI1                 2021
#define IDC_BUTTON_BROWSER_PPT          2022
#define IDC_EDIT_NO                     2022
#define IDC_EDIT_NUM                    2022
#define IDI_ICON_CIHUI2                 2022
#define IDC_COMBO_PATH_RECENT           2022
#define IDC_BUTTON_BROWSER_PDF          2023
#define IDC_EDIT_EMAIL                  2023
#define IDC_BUTTON_BROWSER_TXT          2024
#define IDC_BUTTON_REG                  2024
#define IDI_ICON_REG_INFO               2024
#define IDC_STATIC_BEGINTIME            2025
#define IDC_STATIC_ENDTIME              2026
#define IDI_ICON_FIND                   2026
#define IDC_STATIC_BEGINTIME_CONTENT    2027
#define IDI_ICON_NEW_INDEX              2027
#define IDC_STATIC_ENTTIME_CONTENT      2028
#define IDI_ICON_MODIFY_INDEX           2028
#define IDC_STATIC_ERROR_INFO           2029
#define IDC_STATIC_SEARCH_DIR           2029
#define IDB_BITMAP_OK                   2029
#define IDC_STATIC_OBJECT_TYPE          2030
#define IDB_BITMAP_CANCEL               2030
#define IDC_EDIT_LICENSE_BACK_PATH      2030
#define IDC_STATIC_NEW_WORDS            2031
#define IDB_BITMAP_FOLDER               2031
#define IDC_EDIT_LICENSE_RESTORE_PATH   2031
#define IDC_STATIC_CUSTOM_CIHUI         2032
#define IDB_BITMAP_DELETE               2032
#define IDB_BITMAP_FORWARD              2033
#define IDC_STATIC_CIHUI_1              2034
#define IDI_ICON_HAND                   2034
#define IDC_STATIC_CIHUI_2              2035
#define IDB_BITMAP_CHECK_ALLCIHUI       2035
#define IDC_STATIC_CIHUI_3              2036
#define IDB_BITMAP_CHECK_CIHUI          2036
#define IDC_STATIC_IMPORT_CIHUI         2037
#define IDB_BITMAP_REGISTER             2037
#define IDC_STATIC_SOFT_SET             2038
#define IDB_BITMAP_FOLDER2              2038
#define IDC_STATIC_SET_1                2039
#define IDD_DIALOG_SKIN                 2039
#define IDC_STATIC_LICENSE_INFO         2040
#define IDI_ICON_SKIN                   2040
#define IDC_STATIC_LICENSE_1            2041
#define IDI_ICON_FAST_FIND              2041
#define IDC_STATIC_NUM                  2042
#define IDI_ICON_FAST_SEARCH            2042
#define IDC_STATIC_EMAIL                2043
#define IDC_STATIC_SKIN_SET             2044
#define IDC_STATIC_LICENSE_BACKINFO     2044
#define IDC_STATIC_SKIN_SELECT          2045
#define IDC_STATIC_LICENSE_BACK_TIP     2045
#define IDC_LIST_SKIN                   2046
#define IDC_STATIC_LICENSE_BACK_INFO2   2046
#define IDC_STATIC_SKIN_PREVIEW         2047
#define IDC_STATIC_LICENSE_RESTOREINFO  2047
#define IDC_STATIC_AUTHOR               2048
#define IDC_STATIC_LICENSE_RESTORE_INFO2 2048
#define IDC_STATIC_AUTHOR_NAME          2049
#define IDC_STATIC_LICENSE_RESTORE_TIP  2049
#define IDC_STATIC_HOMEPAGE             2050
#define IDC_STATIC_HOMEPAGE_NAME        2051
#define IDC_STATIC_SKIN_EAMIL           2052
#define IDC_STATIC_SKIN_EAMIL_NAME      2053
#define IDI_ICON_HTML                   2053
#define IDC_STATIC_SEARCH_DIR_MODIFY    2055
#define IDC_STATIC_OBJECT_TYPE_MODIFY   2056
#define IDB_BITMAP_FEIQ_FIND            2057
#define IDB_BITMAP_FEIQ_CLOSE           2058
#define IDC_STATIC_FIND                 2058
#define IDI_ICON_SEARCH_TRAY            2059
#define IDC_STATIC_HAND_LICENSE_BACK    2060
#define IDB_BITMAP_BACK                 2060
#define IDC_BUTTON_LICENSE_BACK         2061
#define IDB_BITMAP_RESTORE              2061
#define IDC_BUTTON_BROWSE_BACK_PATH     2062
#define IDI_ICON_BASIC_SET              2062
#define IDC_STATIC_HAND_LICENSE_RESOTRE 2063
#define IDI_ICON_BASIC_SET2             2063
#define IDC_LOGO                        2063
#define IDC_BUTTON_BROWSE_RESTORE_PATH  2064
#define IDI_ICON_BASIC_SET_NORMAL       2064
#define IDC_BUTTON_LICENSE_RESTORE      2065
#define IDI_ICON_BASIC_SET_DIC          2065
#define IDC_STATIC_BACK                 2065
#define IDI_ICON_BASIC_SET_SKIN         2066
#define IDC_PROGRESS_FAST_SEARCH        2066
#define IDI_ICON_REGISTER               2067
#define IDC_EDIT_PATH                   2067
#define IDI_ICON_REGISTER_INFO          2068
#define IDC_TREE_GROUP                  2068
#define IDI_ICON_FAST_SEARCH2           2069
#define IDI_ICON_FAST_SEARCH3           2070
#define IDI_ICON_POINT2                 2075
#define IDI_ICON_POINT                  2076
#define IDI_ICON_POINT3                 2077
#define IDB_BITMAP_THREME_NAME_2007_Aqua 2078
#define IDB_BITMAP_THREME_NAME_2007_LightBlue 2081
#define IDB_BITMAP_THREME_NAME_VISTA_Black2 2083
#define IDB_BITMAP_THREME_NAME_VISTA_Sliver 2086
#define IDB_BITMAP_THREME_NAME_XP_LUNA_HomeStead 2088
#define IDB_BITMAP_THREME_NAME_XP_LUNA_Metallic 2089
#define IDD_FLOATWND                    2092
#define IDB_BITMAP_LOGO                 2093
#define IDR_MENU_FLOATWND               2094
#define IDB_BITMAP_FASTSEARCHBACK       2095
#define IDD_DIALOG_SAVE_FILE            2096
#define ID_SHOW                         32771
#define ID_HIDE                         32772
#define ID_MENU_NEW_INDEX               32773
#define ID_MENU_SYS_SET                 32774
#define ID_MENU_WEB_QUERY               32775
#define ID_MENU_TRANSPORT               32776
#define ID_MENU_TRANS_100               32777
#define ID_MENU_TRANS_80                32778
#define ID_MENU_TRANS_60                32779
#define ID_MENU_TRANS_40                32780
#define ID_MENU_TRANS_20                32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2097
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         2069
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
